### ISSUE TITLE
ENOENT: no such file or directory, open 'build/reports/lint-results.xml'

### ISSUE THREAD

**Issue by gastsail** [gastsail/CocktailApp#12]
@dionisioedu we have a problem with the Lint check, it always crashes at

`ENOENT: no such file or directory, open 'build/reports/lint-results.xml'`

Can we check it ?

Current PR is not passing : https://github.com/gastsail/CocktailApp/pull/11

**Comment by gastsail** [comment]
hey @dionisioedu any update on this ?

**Comment by dionisioedu** [comment]
Fix on https://github.com/gastsail/CocktailApp/pull/13
