### ISSUE TITLE
Please Expand the README with details of how the architecture works with caching strategy and other important details.

### ISSUE THREAD

**Issue by iudragon** [gastsail/CocktailApp#5]
The repo is meant for architecture and presumably it is meant for other developers to refer it. So can you please add details to README on how the cache strategy is defined, how is the app workflow and other necessary details that you feel are important and would benefit learners like me.

**Comment by gastsail** [comment]
Hey thanks a lot for stopping by 😃  , in the Readme there is an image that specifies the architecture, in the image you can see that you start from the UI layer doing a request that the viewmodel will handle, then the viewmodel is the layer that will communicate with the repository, here, if you see the code there is a DefaultDataSource in which returns the data from the cache and then retrieves fresh data from the server, if you need more details you can check this link

https://developer.android.com/jetpack/guide
