### ISSUE TITLE
[Question] How about the login flow?

### ISSUE THREAD

**Issue by dphans** [gastsail/CocktailApp#6]
Can I ask a question about authentication, aka. login flow?
- User request to backend to get access token.
- Use access token add to retrofit header through okhttp interceptor.
- Save access token into shared preference for later use.

And second question, I heard about recommend that ViewModel will never access to repositories directly, it will call to repositories by usecases (aka. interactors), how about you?

**Comment by gastsail** [comment]
in this repo viewmodel is calling the interceptor (repo interface) that is the abstraction of the repo logic, we are not calling directly to the repo, about login flow you are correct
